// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk3Om6q43phlQN0pTOGElMCegRaGLsSag',
    appId: '1:573337558225:web:6d5846a3cd33d9c7fef9f0',
    messagingSenderId: '573337558225',
    projectId: 'eventlyy-23e9e',
    authDomain: 'eventlyy-23e9e.firebaseapp.com',
    storageBucket: 'eventlyy-23e9e.firebasestorage.app',
    measurementId: 'G-P6P0MC75KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXSaKp7gXHmZ8UtKGdUtSPMSQWoGobSMQ',
    appId: '1:573337558225:android:c4d8853b0800283dfef9f0',
    messagingSenderId: '573337558225',
    projectId: 'eventlyy-23e9e',
    storageBucket: 'eventlyy-23e9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ygbt1sqiwrhzt4rXYq930Kw_Hty9NeE',
    appId: '1:573337558225:ios:1f37ba4ba29c46eefef9f0',
    messagingSenderId: '573337558225',
    projectId: 'eventlyy-23e9e',
    storageBucket: 'eventlyy-23e9e.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ygbt1sqiwrhzt4rXYq930Kw_Hty9NeE',
    appId: '1:573337558225:ios:1f37ba4ba29c46eefef9f0',
    messagingSenderId: '573337558225',
    projectId: 'eventlyy-23e9e',
    storageBucket: 'eventlyy-23e9e.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk3Om6q43phlQN0pTOGElMCegRaGLsSag',
    appId: '1:573337558225:web:dcaf1c3988670eb4fef9f0',
    messagingSenderId: '573337558225',
    projectId: 'eventlyy-23e9e',
    authDomain: 'eventlyy-23e9e.firebaseapp.com',
    storageBucket: 'eventlyy-23e9e.firebasestorage.app',
    measurementId: 'G-9Z1H14P593',
  );

}

